name: dart_sudoku
version: 1.0.2
publish_to: https://onepub.dev/api/zohnoflygz/
description: A simple Dart package or command-line application for solving Sudoku puzzles.
repository: https://github.com/rickgladwin/dart_sudoku
environment: 
  sdk: '>=2.16.2 <3.0.0'
dependencies: 
  ansi_escapes: 
    git:
#      This build corrects a typo. Update to the official release once the version is updated with the fix.
      url: git@github.com:shan-shaji/ansi-escapes-dart.git
      ref: 4f10d5200b74954487c01f623c6113ab39bc7707
  collection: ^1.17.1
dev_dependencies: 
  lints: ^2.0.1
  test: ^1.21.1
